# For more information: https://laravel.com/docs/sail
version: '3'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: laravel-app
        container_name: laravel-app
        restart: unless-stopped
        ports:
            - "8085:8765"
        environment:
            - RUN_MIGRATIONS=${RUN_MIGRATIONS:-true}
        volumes:
            - ./storage:/var/www/html/storage
            - ./docker/php.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - app-network
        depends_on:
            - db
            - redis
            
    db:
        image: 'mariadb:10.6'
        container_name: mariadb-db
        restart: unless-stopped
        ports:
            - "33060:3306"
        environment:
            MYSQL_ROOT_PASSWORD: "${DB_PASSWORD:-secure_db_password}"
            MYSQL_DATABASE: "${DB_DATABASE:-u932436910_bots}"
            MYSQL_USER: "${DB_USERNAME:-u932436910_bots}"
            MYSQL_PASSWORD: "${DB_PASSWORD:-secure_db_password}"
            MYSQL_ALLOW_EMPTY_PASSWORD: "no"
        volumes:
            - mysql-data:/var/lib/mysql
            - ./u932436910_tech.sql:/docker-entrypoint-initdb.d/init.sql
        networks:
            - app-network

    redis:
        image: 'redis:alpine'
        container_name: redis
        restart: unless-stopped
        ports:
            - "63790:6379"
        volumes:
            - redis-data:/data
        networks:
            - app-network

    mailhog:
        image: 'mailhog/mailhog:latest'
        container_name: mailhog
        ports:
            - "10260:1025"
            - "80260:8025"
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    mysql-data:
        driver: local
    redis-data:
        driver: local
